### ISSUE TITLE
deno run errors

### ISSUE THREAD

**Issue by swuecho** [denjucks/denjucks#1]
hwu@amd:~/dev/deno$ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2

Linux amd 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

hello.ts is the script in README.

```
hwu@amd:~/dev/deno$ deno run hello.ts
Compile file:///home/hwu/dev/deno/hello.ts
Compile https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/path/mod.ts
error: TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/path/constants.ts:51:26

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
const isWin = Deno.build.os === "win";
              ~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/path/globrex.ts:5:15

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
      path = env()[`=${resolvedDevice}`] || cwd();
             ~~~
    at https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/path/win32.ts:42:14

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/testing/asserts.ts:382:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://raw.githubusercontent.com/denjucks/denjucks/master/src/deps/path/std/testing/asserts.ts:383:29

Found 5 errors.

```

**Comment by denjucks** [comment]
Thanks for the bug report! I updated the frozen libs to use a newer path module that corrects this error. Let me know if you're still having issues and I'll take another look. For now I'll close this issue
