### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cj81499** [denjucks/denjucks#14]
v1.1.1 has the following error when you try to use it.

> error: Failed to get compiled source code of https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/mod.ts.
> Reason: The system cannot find the path specified. (os error 3)

Can we get a release based on the functional master branch?

**Comment by michaelachrisco** [comment]
I can confirm the same kind of error above. Newest version of deno 1.2.2 has the following error:
```
TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/posix.ts:433:18

Found 6 errors.

```
