### ISSUE TITLE
normalize undefined when trying to render a template

### ISSUE THREAD

**Issue by nthState** [denjucks/denjucks#16]
I'm not sure if this is where I should be posting this, but I keep getting "undefined is not a function"

It's coming from this line:

`ln34: this.searchPaths = searchPaths.map(path.normalize);` in node-loaders

```"TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at new_cls.init (https://deno.land/x/denjucks@1.1.1/src/node-loaders.js:34:44)
    at new new_cls (https://deno.land/x/denjucks@1.1.1/src/object.js:46:28)
    at Object.exports.configure (https://deno.land/x/denjucks@1.1.1/mod.js:40:26)
    at renderDenjuck (denjuck.ts:12:14)
    at Context.ctx.render (oak.ts:54:35)"```

- searchPaths is an array containing one item the path to my templates folder
- path is Symbol(Symbol.toStringTag): "Module"

Running on MacOS

**Comment by nthState** [comment]
I don't understand why, but I managed to get past this error by uninstalled and reinstalling node...of all things

**Comment by Alex0007** [comment]
This error happened to me also (Deno v1.2.3)

When starting my script, i see this warning:
```
Warning Implicitly using latest version (1.1.1) for https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts
```

Command below helped me to fix this:
```
deno cache --no-check https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts
```
