### ISSUE TITLE
Deno 1.2.2 TS2345 error 

### ISSUE THREAD

**Issue by michaelachrisco** [denjucks/denjucks#17]
Newest version of deno 1.2.2 has the following error:
```
TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/posix.ts:433:18

Found 6 errors.

```

**Comment by jdelarubia** [comment]
> Newest version of deno 1.2.2 has the following error:
> 
> ```
> TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
>   Type 'URL' is not assignable to type 'string'.
>   return new URL(url).pathname
>                  ~~~
>     at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/win32.ts:911:18
> 
> TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
>   Type 'URL' is not assignable to type 'string'.
>   return new URL(url).pathname;
>                  ~~~
>     at https://deno.land/x/denjucks@1.1.1/src/deps/path/std/path/posix.ts:433:18
> 
> Found 6 errors.
> ```

Hi @michaelachrisco 
I was having the same problem until I changed my imports to:
```typescript
// @deno-types="https://deno.land/x/denjucks/mod.d.ts"
import denjucks from "https://deno.land/x/denjucks/mod.js";
```

(Now, I'm having other issue, but this went away)

**Comment by buzzeins** [comment]
Another time, same issue.
deno 1.7.0 (release, x86_64-unknown-linux-gnu) 
v8 8.9.255.3
typescript 4.1.3

Any ideas?
