### ISSUE TITLE
Weird proper error handling message

### ISSUE THREAD

**Issue by gjuoun** [denjucks/denjucks#4]
Hi I'm trying to throw a error in denjucks, here is my code 

```ts
const template = `
<!--index.html-->
<body>
  <h1>{{data.name}}</h1>
</body>
`;

denjucks.compile(template).render({}, (err:any, _res:any) => {
  console.log(err)
});
```

Then the error message is 
```js
error: Uncaught TypeError: asap is not a function
    asap(function() { cb(err, res); });
    ^
    at callbackAsap (https://deno.land/x/denjucks/src/environment.js:24:5)
    at https://deno.land/x/denjucks/src/environment.js:498:25
    at new_cls.root [as rootRenderFunc] (eval at _compile (https://deno.land/x/denjucks/src/environment.js:572:24), <anonymous>:19:3)
    at new_cls.render (https://deno.land/x/denjucks/src/environment.js:486:15)
    at file:///C:/Users/gjuoun/Code/github.com.deligenius/view-engine/src/ejs_test.ts:14:28
thread '<unnamed>' panicked at 'cannot access stderr during shutdown', src\libstd\io\stdio.rs:644:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like ```environment.js:24:5``` ```asap()``` function has some issue. 

Is it okay to fix it?

**Comment by denjucks** [comment]
I'll check into this. I think I know where the error is coming from.

**Comment by denjucks** [comment]
Fortunately looks like it was a quick fix. Pushed an update with the fix, can you try again and see if it allows you to handle the error and calls the callback. I tried this code with an error in the template (if statement with no endif) and was able to use the callback:

```javascript
	const template = `
		<!--index.html-->
		<body>
		<!-- If template with no endif error -->
		<h1>{% if %}</h1>
		</body>
	`;

	denjucks.compile(template).render({}, (err, _res) => {
		console.log(err);
		console.log(_res);
	});

```

**Comment by gjuoun** [comment]
Thanks, it works!
